name: Email notifier

on:
  gollum:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Important]')"
    steps:
      - name: test-env
        run: echo "enviar email"
