name: Email notifier

on:
  gollum:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2
  test:
    runs-on: ubuntu-latest
    if: "contains(github.gollum.pages[0].summary, '[Important]')"
    steps:
      - name: test-env
        run: echo "enviar email"
