name: Email notifier

on:
  gollum:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: t
        run: echo "${{ github.event.head_commit.message }}"
  test:
    runs-on: ubuntu-latest
    if: "contains(github.event.pages[0].page_name, '[Change]')"
    steps:
      - name: test-env
        run: echo "enviar email"
